#!/bin/bash

# Cores
verde="\033[1;32m"
azul="\033[1;34m"
reset="\033[0m"

echo -e "${azul}##############################################"
echo -e "# INSTALADOR QBITTORRENT-NOX (WEBUI) by LaelsonCG"
echo -e "# GitHub: https://github.com/LaelsonCG"
echo -e "##############################################${reset}\n"

echo -e "${verde}[+] Atualizando pacotes...${reset}"
sudo apt update -qq && sudo apt upgrade -y -qq

echo -e "${verde}[+] Instalando qbittorrent-nox...${reset}"
if ! apt-cache show qbittorrent-nox > /dev/null 2>&1; then
    echo -e "${verde}[+] Adicionando repositório PPA do qBittorrent...${reset}"
    sudo add-apt-repository -y ppa:qbittorrent-team/qbittorrent-stable > /dev/null 2>&1
    sudo apt update -qq
fi
sudo apt install -y -qq qbittorrent-nox curl > /dev/null

echo -e "${verde}[+] Inicializando qbittorrent-nox para gerar configs...${reset}"
yes | qbittorrent-nox -d
sleep 3
killall qbittorrent-nox

echo -e "${verde}[+] Configurando Web UI para aceitar conexões externas...${reset}"
CONFIG_FILE="/root/.config/qBittorrent/qBittorrent.conf"
mkdir -p "$(dirname "$CONFIG_FILE")"
touch "$CONFIG_FILE"
wget -O /root/.config/qBittorrent/qBittorrent.conf https://raw.githubusercontent.com/LaelsonCG/qbittorrent-web/refs/heads/main/qBittorrent.conf > /dev/null 2>&1

echo -e "${verde}[+] Criando serviço systemd...${reset}"
sudo tee /etc/systemd/system/qbittorrent-nox.service > /dev/null <<EOF
[Unit]
Description=qBittorrent Daemon Service
After=network.target

[Service]
Type=forking
ExecStart=/usr/bin/qbittorrent-nox -d
User=root
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable qbittorrent-nox > /dev/null
sudo systemctl start qbittorrent-nox

ip=$(curl -s -4 ifconfig.me)

echo -e "\n${verde}INSTALAÇÃO CONCLUÍDA.${reset}"
if systemctl is-active --quiet qbittorrent-nox; then
    echo -e "\n${verde}qBittorrent iniciado com sucesso.${reset}"
    echo -e "---------------------------------------------------------------------------"
    echo -e "${azul}ACESSE:${reset} http://${ip}:8080"
    echo -e "${azul}Usuário padrão:${reset} admin"
    echo -e "${azul}Senha padrão:${reset} adminadmin"
    echo -e "Você pode (e deve) alterar as credenciais pela interface web.\n"

else
    echo -e "\n\033[1;31m[ERRO] Falha ao iniciar o serviço qBittorrent.\033[0m"
    systemctl status qbittorrent-nox
fi
